[package]
version = "0.1.0"
name = "game-script"
edition = "2021"
default-run = "server"

[[bin]]
name = "server"
path = "src/bin/main.rs"

[[bin]]
name = "evm"
path = "src/bin/evm.rs"

[[bin]]
name = "vkey"
path = "src/bin/vkey.rs"

[dependencies]
sp1-sdk = { workspace = true }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0.200", default-features = false, features = ["derive"] }
clap = { version = "4.0", features = ["derive", "env"] }
tracing = "0.1.40"
hex = "0.4.3"
alloy-sol-types = { workspace = true }
game-lib = { path = "../lib" }
game-utils = { path = "../utils" }
turbo-sp1 = { path = "../turbo-sp1" }
dotenv = "0.15.0"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
substrate-bn = { git = "https://github.com/sp1-patches/bn", tag = "patch-0.6.0-sp1-4.0.0" }
bls12_381 = { git = "https://github.com/sp1-patches/bls12_381", tag = "patch-0.8.0-sp1-4.0.0-v2", features = [
  "experimental",
] }
rand = "0.8"

agent-random = { path = "../agent-random" }
agent-minimax = { path = "../agent-minimax" }

[build-dependencies]
sp1-build = "4.1.7"
